# Generated by Django 4.2.11 on 2025-12-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='director',
        ),
        migrations.AddField(
            model_name='movies',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='rate_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='tmdb_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
