# Generated by Django 4.2.11 on 2025-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyletter', '0002_remove_movies_director_movies_poster_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedmovies',
            name='my_review',
            field=models.TextField(null=True),
        ),
    ]
